Fixes readme

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -1,1 +1,9 @@
-bundle exec cap production deploy
+#!/usr/bin/env bash
+
+if [[ ! $(git remote) =~ /origin2/ ]]; then
+  echo "ERROR: no 'origin' remote was found"
+  exit 1
+fi
+
+bundle exec rake build
+bundle exec rake publish
